-- =====================================================
-- 01_create_dw.sql
-- Camada final do Data Warehouse - esquema estrela
-- Projeto academico de Data Warehouse para locadora
-- Grupo:
--   Tadeu Belfort Neto              DRE 119034813
--   Vicente Alves                   DRE 120044148
--   João Pedro de Lacerda           DRE 116076670
-- Este script recria o schema dw e seus objetos finais.
-- As dimensoes sao conformadas e compartilhadas entre as fatos.
--
-- ⚠️  AVISO: SCRIPT DESTRUTIVO. O DROP SCHEMA dw CASCADE abaixo APAGA
--     todo o DW (dados, tabelas e sequências IDENTITY). Os surrogate
--     keys são REGENERADOS do zero a cada execução — qualquer referência
--     externa a SKs (relatórios/BI que tenham guardado SK) será quebrada.
--     NÃO executar em produção sem intenção explícita de rebuild total.
--
-- MODELAGEM: esquema estrela com um ramo snowflake — dim_veiculo
--     referencia dim_grupo_veiculo e dim_empresa. As fatos também
--     carregam sk_grupo_veiculo/sk_empresa de forma redundante (atalho
--     de consulta). Os dois caminhos devem permanecer consistentes:
--     a carga (02_load_dimensoes/03_load_fatos) resolve ambos a partir
--     das mesmas chaves naturais conformadas, garantindo isso.
--
-- SCD: todas as dimensões são SCD TYPE 1 (sobrescrita via ON CONFLICT
--     DO UPDATE na carga). NÃO há versionamento histórico. Consequência:
--     o DW reflete sempre o estado ATUAL de cada dimensão, não o estado
--     vigente na época do fato. Ver notas por dimensão abaixo.
--
-- Transação: todo o create roda em BEGIN/COMMIT para que a recriação
--     seja atômica (se algo falhar no meio, nada fica pela metade).
-- =====================================================

BEGIN;

DROP SCHEMA IF EXISTS dw CASCADE;
CREATE SCHEMA dw;

-- =====================================================
-- Dimensao de tempo
-- Grao: um dia.
-- =====================================================
CREATE TABLE dw.dim_tempo (
    sk_tempo             INTEGER      NOT NULL,
    data                 DATE         NOT NULL,
    ano                  INTEGER      NOT NULL,
    mes                  INTEGER      NOT NULL,
    nome_mes             VARCHAR(20)  NOT NULL,
    trimestre            INTEGER      NOT NULL,
    dia                  INTEGER      NOT NULL,
    dia_semana           INTEGER      NOT NULL,
    nome_dia_semana      VARCHAR(20)  NOT NULL,
    flag_fim_de_semana   BOOLEAN      NOT NULL,

    CONSTRAINT pk_dim_tempo PRIMARY KEY (sk_tempo),
    CONSTRAINT uq_dim_tempo_data UNIQUE (data)
);

COMMENT ON TABLE dw.dim_tempo IS
'Dimensao conformada de tempo com granularidade diaria.';

-- =====================================================
-- Dimensao de cliente
-- cliente_id recebe a chave natural conformada cliente_nk
-- criada na transformacao: grupo_fonte-src_id.
-- =====================================================
CREATE TABLE dw.dim_cliente (
    sk_cliente          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cliente_id          TEXT         NOT NULL,
    nome                TEXT         NOT NULL,
    tipo                VARCHAR(10)  NOT NULL,
    cidade              TEXT,
    -- TRUE quando o nome foi preenchido por sentinela (origem vazia/nula).
    flag_nome_imputado  BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_dim_cliente PRIMARY KEY (sk_cliente),
    CONSTRAINT uq_dim_cliente_cliente_id UNIQUE (cliente_id)
);

COMMENT ON TABLE dw.dim_cliente IS
'Dimensao conformada de clientes (SCD Tipo 1: sobrescrita, sem historico). '
'A chave natural cliente_id vem de stg.conf_cliente.cliente_nk. '
'ATENCAO: mudancas de cidade do cliente sao sobrescritas; para analisar '
'onde o cliente morava na epoca da locacao seria necessario SCD Tipo 2.';

-- =====================================================
-- Dimensao de condutor
-- =====================================================
CREATE TABLE dw.dim_condutor (
    sk_condutor     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    condutor_id     TEXT        NOT NULL,
    cliente_id      TEXT        NOT NULL,
    nome            TEXT        NOT NULL,
    categoria_cnh   VARCHAR(10),
    validade_cnh    DATE,

    CONSTRAINT pk_dim_condutor PRIMARY KEY (sk_condutor),
    CONSTRAINT uq_dim_condutor_condutor_id UNIQUE (condutor_id)
);

COMMENT ON TABLE dw.dim_condutor IS
'Dimensao conformada de condutores. Mantem cliente_id natural para rastreabilidade.';

-- =====================================================
-- Dimensao de grupo de veiculo
-- =====================================================
CREATE TABLE dw.dim_grupo_veiculo (
    sk_grupo_veiculo   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    grupo_id           TEXT        NOT NULL,
    nome               TEXT        NOT NULL,
    categoria          TEXT        NOT NULL,

    CONSTRAINT pk_dim_grupo_veiculo PRIMARY KEY (sk_grupo_veiculo),
    CONSTRAINT uq_dim_grupo_veiculo_grupo_id UNIQUE (grupo_id)
);

COMMENT ON TABLE dw.dim_grupo_veiculo IS
'Dimensao conformada dos grupos/categorias comerciais de veiculo.';

-- =====================================================
-- Dimensao de empresa
-- A transformacao atual nao traz CNPJ consolidado; o campo fica
-- disponivel para evolucao da carga sem alterar o modelo dimensional.
-- =====================================================
CREATE TABLE dw.dim_empresa (
    sk_empresa   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    empresa_id   TEXT NOT NULL,
    nome         TEXT NOT NULL,
    cnpj         TEXT,

    CONSTRAINT pk_dim_empresa PRIMARY KEY (sk_empresa),
    CONSTRAINT uq_dim_empresa_empresa_id UNIQUE (empresa_id)
);

COMMENT ON TABLE dw.dim_empresa IS
'Dimensao conformada de empresas locadoras.';

-- =====================================================
-- Dimensao de patio
-- =====================================================
CREATE TABLE dw.dim_patio (
    sk_patio   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    patio_id   TEXT NOT NULL,
    nome       TEXT NOT NULL,
    cidade     TEXT,

    CONSTRAINT pk_dim_patio PRIMARY KEY (sk_patio),
    CONSTRAINT uq_dim_patio_patio_id UNIQUE (patio_id)
);

COMMENT ON TABLE dw.dim_patio IS
'Dimensao conformada dos patios de retirada, devolucao e movimentacao.';

-- =====================================================
-- Dimensao de veiculo
-- Compartilha as dimensoes conformadas de grupo e empresa.
-- =====================================================
CREATE TABLE dw.dim_veiculo (
    sk_veiculo             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    veiculo_id             TEXT         NOT NULL,
    placa                  TEXT         NOT NULL,
    chassi                 TEXT,
    marca                  TEXT         NOT NULL,
    modelo                 TEXT         NOT NULL,
    cor                    TEXT,
    tipo_mecanizacao       VARCHAR(30)  NOT NULL,
    ar_condicionado        BOOLEAN      NOT NULL,
    adaptado_cadeirante    BOOLEAN      NOT NULL,
    status                 VARCHAR(30)  NOT NULL,
    -- TRUE quando a placa foi preenchida por sentinela ('SEMPLACA').
    flag_placa_imputada    BOOLEAN      NOT NULL DEFAULT FALSE,
    sk_grupo_veiculo       BIGINT       NOT NULL,
    sk_empresa             BIGINT       NOT NULL,

    CONSTRAINT pk_dim_veiculo PRIMARY KEY (sk_veiculo),
    CONSTRAINT uq_dim_veiculo_veiculo_id UNIQUE (veiculo_id),
    CONSTRAINT fk_dim_veiculo_grupo
        FOREIGN KEY (sk_grupo_veiculo) REFERENCES dw.dim_grupo_veiculo (sk_grupo_veiculo),
    CONSTRAINT fk_dim_veiculo_empresa
        FOREIGN KEY (sk_empresa) REFERENCES dw.dim_empresa (sk_empresa)
);

COMMENT ON TABLE dw.dim_veiculo IS
'Dimensao conformada de veiculos (SCD Tipo 1), ligada a grupo e empresa. '
'ATENCAO: a coluna status e um atributo OPERACIONAL VOLATIL '
'(alugado/disponivel/manutencao) sobrescrito a cada carga — reflete apenas '
'o estado ATUAL, nao o vigente na epoca do fato. Para historico de status '
'use a fato_veiculo_no_patio (snapshot) em vez deste atributo.';

-- =====================================================
-- Fato de reservas
-- Grao: uma reserva.
-- =====================================================
CREATE TABLE dw.fato_reserva (
    sk_fato_reserva       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reserva_id            TEXT        NOT NULL,
    sk_cliente            BIGINT      NOT NULL,
    sk_grupo_veiculo      BIGINT      NOT NULL,
    sk_patio_retirada     BIGINT      NOT NULL,
    sk_patio_devolucao    BIGINT,
    sk_tempo_inicio       INTEGER     NOT NULL,
    sk_tempo_fim          INTEGER,
    status_reserva        VARCHAR(30) NOT NULL,
    qtd_reservas          INTEGER     NOT NULL DEFAULT 1,
    dias_reservados       INTEGER,
    flag_cancelada        BOOLEAN     NOT NULL DEFAULT FALSE,
    flag_confirmada       BOOLEAN     NOT NULL DEFAULT FALSE,
    flag_espera           BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_fato_reserva PRIMARY KEY (sk_fato_reserva),
    CONSTRAINT uq_fato_reserva_reserva_id UNIQUE (reserva_id),
    CONSTRAINT fk_fato_reserva_cliente
        FOREIGN KEY (sk_cliente) REFERENCES dw.dim_cliente (sk_cliente),
    CONSTRAINT fk_fato_reserva_grupo
        FOREIGN KEY (sk_grupo_veiculo) REFERENCES dw.dim_grupo_veiculo (sk_grupo_veiculo),
    CONSTRAINT fk_fato_reserva_patio_retirada
        FOREIGN KEY (sk_patio_retirada) REFERENCES dw.dim_patio (sk_patio),
    CONSTRAINT fk_fato_reserva_patio_devolucao
        FOREIGN KEY (sk_patio_devolucao) REFERENCES dw.dim_patio (sk_patio),
    CONSTRAINT fk_fato_reserva_tempo_inicio
        FOREIGN KEY (sk_tempo_inicio) REFERENCES dw.dim_tempo (sk_tempo),
    CONSTRAINT fk_fato_reserva_tempo_fim
        FOREIGN KEY (sk_tempo_fim) REFERENCES dw.dim_tempo (sk_tempo)
);

COMMENT ON TABLE dw.fato_reserva IS
'Fato analitica de reservas, com flags de status e dias reservados.';

-- =====================================================
-- Fato de locacoes
-- Grao: uma locacao.
-- =====================================================
CREATE TABLE dw.fato_locacao (
    sk_fato_locacao                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    locacao_id                      TEXT        NOT NULL,
    reserva_id                      TEXT,
    sk_cliente                      BIGINT      NOT NULL,
    sk_condutor                     BIGINT      NOT NULL,
    sk_veiculo                      BIGINT      NOT NULL,
    sk_grupo_veiculo                BIGINT      NOT NULL,
    sk_empresa                      BIGINT      NOT NULL,
    sk_patio_retirada               BIGINT      NOT NULL,
    sk_patio_devolucao              BIGINT,
    sk_tempo_retirada_prevista      INTEGER,
    sk_tempo_retirada_realizada     INTEGER,
    sk_tempo_devolucao_prevista     INTEGER,
    sk_tempo_devolucao_realizada    INTEGER,
    km_entrega                      INTEGER,
    km_devolucao                    INTEGER,
    km_rodado                       INTEGER,
    dias_previstos                  INTEGER,
    dias_realizados                 INTEGER,
    atraso_devolucao_dias           INTEGER,
    qtd_locacoes                    INTEGER     NOT NULL DEFAULT 1,
    valor_cobranca                  NUMERIC(12,2),
    -- Multa por atraso (regra de negócio calculada em stg.conf_locacao):
    -- valor cobrado na origem ou estimado por dias_atraso × diária do grupo.
    valor_multa_atraso              NUMERIC(12,2),
    status_cobranca                 VARCHAR(30),

    CONSTRAINT pk_fato_locacao PRIMARY KEY (sk_fato_locacao),
    CONSTRAINT uq_fato_locacao_locacao_id UNIQUE (locacao_id),
    CONSTRAINT fk_fato_locacao_cliente
        FOREIGN KEY (sk_cliente) REFERENCES dw.dim_cliente (sk_cliente),
    CONSTRAINT fk_fato_locacao_condutor
        FOREIGN KEY (sk_condutor) REFERENCES dw.dim_condutor (sk_condutor),
    CONSTRAINT fk_fato_locacao_veiculo
        FOREIGN KEY (sk_veiculo) REFERENCES dw.dim_veiculo (sk_veiculo),
    CONSTRAINT fk_fato_locacao_grupo
        FOREIGN KEY (sk_grupo_veiculo) REFERENCES dw.dim_grupo_veiculo (sk_grupo_veiculo),
    CONSTRAINT fk_fato_locacao_empresa
        FOREIGN KEY (sk_empresa) REFERENCES dw.dim_empresa (sk_empresa),
    CONSTRAINT fk_fato_locacao_patio_retirada
        FOREIGN KEY (sk_patio_retirada) REFERENCES dw.dim_patio (sk_patio),
    CONSTRAINT fk_fato_locacao_patio_devolucao
        FOREIGN KEY (sk_patio_devolucao) REFERENCES dw.dim_patio (sk_patio),
    CONSTRAINT fk_fato_locacao_tempo_ret_prev
        FOREIGN KEY (sk_tempo_retirada_prevista) REFERENCES dw.dim_tempo (sk_tempo),
    CONSTRAINT fk_fato_locacao_tempo_ret_real
        FOREIGN KEY (sk_tempo_retirada_realizada) REFERENCES dw.dim_tempo (sk_tempo),
    CONSTRAINT fk_fato_locacao_tempo_dev_prev
        FOREIGN KEY (sk_tempo_devolucao_prevista) REFERENCES dw.dim_tempo (sk_tempo),
    CONSTRAINT fk_fato_locacao_tempo_dev_real
        FOREIGN KEY (sk_tempo_devolucao_realizada) REFERENCES dw.dim_tempo (sk_tempo)
);

COMMENT ON TABLE dw.fato_locacao IS
'Fato analitica de locacoes, com medidas de quilometragem, dias, atraso e cobranca.';

-- =====================================================
-- Fato de movimentacao de veiculo entre patios
-- Grao: uma movimentacao registrada entre patios.
-- movimentacao_patio_id preserva a chave natural da origem transformada.
-- =====================================================
CREATE TABLE dw.fato_veiculo_no_patio (
    sk_fato_veiculo_no_patio   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    movimentacao_patio_id      TEXT    NOT NULL,
    sk_veiculo                 BIGINT  NOT NULL,
    sk_patio_origem            BIGINT  NOT NULL,
    sk_patio_destino           BIGINT  NOT NULL,
    sk_tempo_movimentacao      INTEGER NOT NULL,
    motivo                     TEXT,
    qtd_movimentacoes          INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT pk_fato_veiculo_no_patio PRIMARY KEY (sk_fato_veiculo_no_patio),
    CONSTRAINT uq_fato_veiculo_no_patio_movimentacao_id UNIQUE (movimentacao_patio_id),
    CONSTRAINT fk_fato_veiculo_no_patio_veiculo
        FOREIGN KEY (sk_veiculo) REFERENCES dw.dim_veiculo (sk_veiculo),
    CONSTRAINT fk_fato_veiculo_no_patio_origem
        FOREIGN KEY (sk_patio_origem) REFERENCES dw.dim_patio (sk_patio),
    CONSTRAINT fk_fato_veiculo_no_patio_destino
        FOREIGN KEY (sk_patio_destino) REFERENCES dw.dim_patio (sk_patio),
    CONSTRAINT fk_fato_veiculo_no_patio_tempo
        FOREIGN KEY (sk_tempo_movimentacao) REFERENCES dw.dim_tempo (sk_tempo)
);

COMMENT ON TABLE dw.fato_veiculo_no_patio IS
'Fato de movimentacoes entre patios, usada para analise de transicao de veiculos.';

-- =====================================================
-- Indices nas FKs das fatos
-- =====================================================
CREATE INDEX idx_fato_reserva_cliente
    ON dw.fato_reserva (sk_cliente);
CREATE INDEX idx_fato_reserva_grupo
    ON dw.fato_reserva (sk_grupo_veiculo);
CREATE INDEX idx_fato_reserva_patio_retirada
    ON dw.fato_reserva (sk_patio_retirada);
CREATE INDEX idx_fato_reserva_patio_devolucao
    ON dw.fato_reserva (sk_patio_devolucao);
CREATE INDEX idx_fato_reserva_tempo_inicio
    ON dw.fato_reserva (sk_tempo_inicio);
CREATE INDEX idx_fato_reserva_tempo_fim
    ON dw.fato_reserva (sk_tempo_fim);

CREATE INDEX idx_fato_locacao_cliente
    ON dw.fato_locacao (sk_cliente);
CREATE INDEX idx_fato_locacao_condutor
    ON dw.fato_locacao (sk_condutor);
CREATE INDEX idx_fato_locacao_veiculo
    ON dw.fato_locacao (sk_veiculo);
CREATE INDEX idx_fato_locacao_grupo
    ON dw.fato_locacao (sk_grupo_veiculo);
CREATE INDEX idx_fato_locacao_empresa
    ON dw.fato_locacao (sk_empresa);
CREATE INDEX idx_fato_locacao_patio_retirada
    ON dw.fato_locacao (sk_patio_retirada);
CREATE INDEX idx_fato_locacao_patio_devolucao
    ON dw.fato_locacao (sk_patio_devolucao);
CREATE INDEX idx_fato_locacao_tempo_ret_prev
    ON dw.fato_locacao (sk_tempo_retirada_prevista);
CREATE INDEX idx_fato_locacao_tempo_ret_real
    ON dw.fato_locacao (sk_tempo_retirada_realizada);
CREATE INDEX idx_fato_locacao_tempo_dev_prev
    ON dw.fato_locacao (sk_tempo_devolucao_prevista);
CREATE INDEX idx_fato_locacao_tempo_dev_real
    ON dw.fato_locacao (sk_tempo_devolucao_realizada);

CREATE INDEX idx_fato_veiculo_no_patio_veiculo
    ON dw.fato_veiculo_no_patio (sk_veiculo);
CREATE INDEX idx_fato_veiculo_no_patio_origem
    ON dw.fato_veiculo_no_patio (sk_patio_origem);
CREATE INDEX idx_fato_veiculo_no_patio_destino
    ON dw.fato_veiculo_no_patio (sk_patio_destino);
CREATE INDEX idx_fato_veiculo_no_patio_tempo
    ON dw.fato_veiculo_no_patio (sk_tempo_movimentacao);

COMMIT;
